version: "3.8"
name: miomock
services:
  pg:
    platform: linux/arm64
    image: postgres:18
    container_name: miomock-pg
    volumes:
      - ./fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql # DB 초기화 스크립트 (얘가 있어야 데이터베이스(schema)가 생깁니다)
    environment:
      POSTGRES_DB: miomock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miomock123
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
