# database/docker-compose.yml (pgvector 적용)
name: miomock
services:
  pg:
    image: public.ecr.aws/m9z8n2p9/cartanova/sonamu-postgres:latest
    container_name: miomock-pg
    volumes:
      - ./fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: template1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miomock123
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
