# database/docker-compose.yml (pgvector 적용)
name: miomock
services:
  pg:
    platform: linux/arm64
    image: pgvector/pgvector:pg18
    container_name: miomock-pg
    volumes:
      - ./fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: miomock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miomock123
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
