/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestResultsRouteImport } from './routes/test-results'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ScaffoldingRouteImport } from './routes/scaffolding'
import { Route as MigrationsRouteImport } from './routes/migrations'
import { Route as I18nRouteImport } from './routes/i18n'
import { Route as FixtureRouteImport } from './routes/fixture'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as CddRouteImport } from './routes/cdd'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksWorkflowRunIdRouteImport } from './routes/tasks_.$workflowRunId'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities/$entityId'

const TestResultsRoute = TestResultsRouteImport.update({
  id: '/test-results',
  path: '/test-results',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScaffoldingRoute = ScaffoldingRouteImport.update({
  id: '/scaffolding',
  path: '/scaffolding',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsRoute = MigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const I18nRoute = I18nRouteImport.update({
  id: '/i18n',
  path: '/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const FixtureRoute = FixtureRouteImport.update({
  id: '/fixture',
  path: '/fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const CddRoute = CddRouteImport.update({
  id: '/cdd',
  path: '/cdd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksWorkflowRunIdRoute = TasksWorkflowRunIdRouteImport.update({
  id: '/tasks_/$workflowRunId',
  path: '/tasks/$workflowRunId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/$entityId',
  path: '/$entityId',
  getParentRoute: () => EntitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cdd': typeof CddRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/i18n': typeof I18nRoute
  '/migrations': typeof MigrationsRoute
  '/scaffolding': typeof ScaffoldingRoute
  '/tasks': typeof TasksRoute
  '/test-results': typeof TestResultsRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/tasks/$workflowRunId': typeof TasksWorkflowRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cdd': typeof CddRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/i18n': typeof I18nRoute
  '/migrations': typeof MigrationsRoute
  '/scaffolding': typeof ScaffoldingRoute
  '/tasks': typeof TasksRoute
  '/test-results': typeof TestResultsRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/tasks/$workflowRunId': typeof TasksWorkflowRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cdd': typeof CddRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/i18n': typeof I18nRoute
  '/migrations': typeof MigrationsRoute
  '/scaffolding': typeof ScaffoldingRoute
  '/tasks': typeof TasksRoute
  '/test-results': typeof TestResultsRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/tasks_/$workflowRunId': typeof TasksWorkflowRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cdd'
    | '/entities'
    | '/fixture'
    | '/i18n'
    | '/migrations'
    | '/scaffolding'
    | '/tasks'
    | '/test-results'
    | '/entities/$entityId'
    | '/tasks/$workflowRunId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cdd'
    | '/entities'
    | '/fixture'
    | '/i18n'
    | '/migrations'
    | '/scaffolding'
    | '/tasks'
    | '/test-results'
    | '/entities/$entityId'
    | '/tasks/$workflowRunId'
  id:
    | '__root__'
    | '/'
    | '/cdd'
    | '/entities'
    | '/fixture'
    | '/i18n'
    | '/migrations'
    | '/scaffolding'
    | '/tasks'
    | '/test-results'
    | '/entities/$entityId'
    | '/tasks_/$workflowRunId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CddRoute: typeof CddRoute
  EntitiesRoute: typeof EntitiesRouteWithChildren
  FixtureRoute: typeof FixtureRoute
  I18nRoute: typeof I18nRoute
  MigrationsRoute: typeof MigrationsRoute
  ScaffoldingRoute: typeof ScaffoldingRoute
  TasksRoute: typeof TasksRoute
  TestResultsRoute: typeof TestResultsRoute
  TasksWorkflowRunIdRoute: typeof TasksWorkflowRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-results': {
      id: '/test-results'
      path: '/test-results'
      fullPath: '/test-results'
      preLoaderRoute: typeof TestResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scaffolding': {
      id: '/scaffolding'
      path: '/scaffolding'
      fullPath: '/scaffolding'
      preLoaderRoute: typeof ScaffoldingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations': {
      id: '/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof MigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i18n': {
      id: '/i18n'
      path: '/i18n'
      fullPath: '/i18n'
      preLoaderRoute: typeof I18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixture': {
      id: '/fixture'
      path: '/fixture'
      fullPath: '/fixture'
      preLoaderRoute: typeof FixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdd': {
      id: '/cdd'
      path: '/cdd'
      fullPath: '/cdd'
      preLoaderRoute: typeof CddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks_/$workflowRunId': {
      id: '/tasks_/$workflowRunId'
      path: '/tasks/$workflowRunId'
      fullPath: '/tasks/$workflowRunId'
      preLoaderRoute: typeof TasksWorkflowRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof EntitiesRoute
    }
  }
}

interface EntitiesRouteChildren {
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CddRoute: CddRoute,
  EntitiesRoute: EntitiesRouteWithChildren,
  FixtureRoute: FixtureRoute,
  I18nRoute: I18nRoute,
  MigrationsRoute: MigrationsRoute,
  ScaffoldingRoute: ScaffoldingRoute,
  TasksRoute: TasksRoute,
  TestResultsRoute: TestResultsRoute,
  TasksWorkflowRunIdRoute: TasksWorkflowRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
