/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScaffoldingRouteImport } from './routes/scaffolding'
import { Route as MigrationsRouteImport } from './routes/migrations'
import { Route as FixtureRouteImport } from './routes/fixture'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities/$entityId'

const ScaffoldingRoute = ScaffoldingRouteImport.update({
  id: '/scaffolding',
  path: '/scaffolding',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsRoute = MigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FixtureRoute = FixtureRouteImport.update({
  id: '/fixture',
  path: '/fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/$entityId',
  path: '/$entityId',
  getParentRoute: () => EntitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/migrations': typeof MigrationsRoute
  '/scaffolding': typeof ScaffoldingRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/migrations': typeof MigrationsRoute
  '/scaffolding': typeof ScaffoldingRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/fixture': typeof FixtureRoute
  '/migrations': typeof MigrationsRoute
  '/scaffolding': typeof ScaffoldingRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entities'
    | '/fixture'
    | '/migrations'
    | '/scaffolding'
    | '/entities/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entities'
    | '/fixture'
    | '/migrations'
    | '/scaffolding'
    | '/entities/$entityId'
  id:
    | '__root__'
    | '/'
    | '/entities'
    | '/fixture'
    | '/migrations'
    | '/scaffolding'
    | '/entities/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntitiesRoute: typeof EntitiesRouteWithChildren
  FixtureRoute: typeof FixtureRoute
  MigrationsRoute: typeof MigrationsRoute
  ScaffoldingRoute: typeof ScaffoldingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scaffolding': {
      id: '/scaffolding'
      path: '/scaffolding'
      fullPath: '/scaffolding'
      preLoaderRoute: typeof ScaffoldingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations': {
      id: '/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof MigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixture': {
      id: '/fixture'
      path: '/fixture'
      fullPath: '/fixture'
      preLoaderRoute: typeof FixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof EntitiesRoute
    }
  }
}

interface EntitiesRouteChildren {
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntitiesRoute: EntitiesRouteWithChildren,
  FixtureRoute: FixtureRoute,
  MigrationsRoute: MigrationsRoute,
  ScaffoldingRoute: ScaffoldingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
