compressionLevel: mixed
enableGlobalCache: false
nmHoistingLimits: workspaces
nodeLinker: pnp

pnpIgnorePatterns:
  - examples/pp1/web
  - "**/template/*" # create-sonamu/template

pnpUnpluggedFolder: ./.yarn/unplugged
pnpMode: loose

# Yarn workspace 전환 이후로 발생한 문제를 해결하기 위한 workaround입니다.
# 조금 지저분하지만, 이렇게 하지 않으면 yarn build시 수많은 MODULE_NOT_FOUND를 만날 수 있습니다.
# 더 나은 방법이 있다면 고쳐주세요.
packageExtensions:
  "@types/react@*":
    dependencies:
      prop-types: "*"
  "@types/lodash-es@*":
    dependencies:
      lodash: "*"
  "@types/react-dom@*":
    dependencies:
      react: "*"
  "react-semantic-ui-datepickers@*":
    dependencies:
      react: "*"
      semantic-ui-react: "*"
    peerDependencies:
      react: "*"
      semantic-ui-react: "*"
  "dayzed@*":
    dependencies:
      prop-types: "*"
  "vite@*":
    dependencies:
      supports-color: "*"
  "debug@*":
    dependencies:
      supports-color: "*"
  "@types/node@*":
    dependencies:
      buffer: "*"
      punycode: "*"
      string_decoder: "*"
  "undici-types@*":
    dependencies:
      buffer: "*"
  "fastify@*":
    dependencies:
      buffer: "*"
  "@fastify/cors@*":
    dependencies:
      fastify: "*"
  "@fastify/formbody@*":
    dependencies:
      fastify: "*"
  "fastify-qs@*":
    dependencies:
      fastify: "*"
      "@types/qs": "*"
  "@fastify/multipart@*":
    dependencies:
      fastify: "*"
  "@fastify/static@*":
    dependencies:
      fastify: "*"
  "@types/react-syntax-highlighter@*":
    dependencies:
      react: "*"
  "node-fetch@*":
    dependencies:
      encoding: "*"

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js"
