compressionLevel: mixed
enableGlobalCache: false
nmHoistingLimits: workspaces
nodeLinker: pnp

pnpIgnorePatterns:
  - examples/pp1/web
  - "**/template/*" # create-sonamu/template

pnpUnpluggedFolder: ./.yarn/unplugged
pnpMode: loose

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js"
