compressionLevel: mixed
enableGlobalCache: false
nmHoistingLimits: workspaces
nodeLinker: pnp

pnpIgnorePatterns:
  - "**/template/*" # create-sonamu/template

pnpUnpluggedFolder: ./.yarn/unplugged
pnpMode: loose

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js"

# packageExtensions: Fixes for third-party packages with broken dependency declarations
# All of these are required to eliminate MODULE_NOT_FOUND errors in Yarn PnP strict mode
packageExtensions:
  # @types packages missing dependencies
  "@types/react@*":
    dependencies:
      prop-types: "*"
  "@types/react-dom@*":
    dependencies:
      react: "*"
  "@types/react-syntax-highlighter@*":
    dependencies:
      react: "*"
  "@types/lodash-es@*":
    dependencies:
      lodash: "*"

  # @types/node and undici-types trying to access Node builtins in non-Node context
  "@types/node@*":
    dependencies:
      buffer: "*"
      punycode: "*"
      string_decoder: "*"
  "undici-types@*":
    dependencies:
      buffer: "*"
  "fastify@*":
    dependencies:
      buffer: "*"

  # UI library peer dependencies not properly declared
  "react-semantic-ui-datepickers@*":
    peerDependencies:
      react: "*"
      semantic-ui-react: "*"
  "dayzed@*":
    dependencies:
      prop-types: "*"

  # Build tools missing color support
  "vite@*":
    dependencies:
      supports-color: "*"
  "debug@*":
    dependencies:
      supports-color: "*"

  # Fastify plugins not declaring fastify dependency
  "@fastify/cors@*":
    peerDependencies:
      fastify: "*"
  "@fastify/formbody@*":
    peerDependencies:
      fastify: "*"
  "@fastify/multipart@*":
    peerDependencies:
      fastify: "*"
  "@fastify/static@*":
    peerDependencies:
      fastify: "*"
  "fastify-qs@*":
    peerDependencies:
      fastify: "*"
      "@types/qs": "*"

