compressionLevel: mixed
enableGlobalCache: false
nmHoistingLimits: workspaces
nodeLinker: pnp

pnpIgnorePatterns:
  - "**/template/*" # create-sonamu/template

pnpUnpluggedFolder: ./.yarn/unplugged
pnpMode: loose

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js"

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"
  react-semantic-ui-datepickers@*:
    dependencies:
      react: "*"
      semantic-ui-react: "*"
  dazed@*:
    dependencies:
      react: "*"
      prop-types: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
