/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as FormRouteImport } from './routes/form'
import { Route as DialogsAlertsRouteImport } from './routes/dialogs-alerts'
import { Route as DataDisplayRouteImport } from './routes/data-display'
import { Route as IndexRouteImport } from './routes/index'

const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogsAlertsRoute = DialogsAlertsRouteImport.update({
  id: '/dialogs-alerts',
  path: '/dialogs-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDisplayRoute = DataDisplayRouteImport.update({
  id: '/data-display',
  path: '/data-display',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-display': typeof DataDisplayRoute
  '/dialogs-alerts': typeof DialogsAlertsRoute
  '/form': typeof FormRoute
  '/layout': typeof LayoutRoute
  '/navigation': typeof NavigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-display': typeof DataDisplayRoute
  '/dialogs-alerts': typeof DialogsAlertsRoute
  '/form': typeof FormRoute
  '/layout': typeof LayoutRoute
  '/navigation': typeof NavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-display': typeof DataDisplayRoute
  '/dialogs-alerts': typeof DialogsAlertsRoute
  '/form': typeof FormRoute
  '/layout': typeof LayoutRoute
  '/navigation': typeof NavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-display'
    | '/dialogs-alerts'
    | '/form'
    | '/layout'
    | '/navigation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-display'
    | '/dialogs-alerts'
    | '/form'
    | '/layout'
    | '/navigation'
  id:
    | '__root__'
    | '/'
    | '/data-display'
    | '/dialogs-alerts'
    | '/form'
    | '/layout'
    | '/navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataDisplayRoute: typeof DataDisplayRoute
  DialogsAlertsRoute: typeof DialogsAlertsRoute
  FormRoute: typeof FormRoute
  LayoutRoute: typeof LayoutRoute
  NavigationRoute: typeof NavigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogs-alerts': {
      id: '/dialogs-alerts'
      path: '/dialogs-alerts'
      fullPath: '/dialogs-alerts'
      preLoaderRoute: typeof DialogsAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-display': {
      id: '/data-display'
      path: '/data-display'
      fullPath: '/data-display'
      preLoaderRoute: typeof DataDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataDisplayRoute: DataDisplayRoute,
  DialogsAlertsRoute: DialogsAlertsRoute,
  FormRoute: FormRoute,
  LayoutRoute: LayoutRoute,
  NavigationRoute: NavigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
