// tsup.config.js
import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts", "src/bin/cli.ts", "src/bin/cli-wrapper.ts"],
  dts: false,
  format: ["esm"],
  target: "esnext",
  clean: true,
  sourcemap: true,
  platform: "node",
  splitting: false,
  external: [
    "@aws-sdk/client-s3",
    "@aws-sdk/s3-request-presigner",
    "@fastify/cors",
    "@fastify/formbody",
    "@fastify/multipart",
    "@fastify/passport",
    "@fastify/secure-session",
    "@fastify/static",
    "chalk",
    "chokidar",
    "date-fns",
    "date-fns-tz",
    "dotenv",
    "fast-deep-equal",
    "fastify",
    "fastify-qs",
    "fastify-sse-v2",
    "flydrive",
    "inflection",
    "knex",
    "lodash-es",
    "luxon",
    "mime-types",
    "minimatch",
    "mysql2",
    "node-sql-parser",
    "nodemon",
    "prompts",
    "qs",
    "tsicli",
    "vitest",
    "zod",
    "typescript", // ← 추가!
  ],
});
