/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by @tanstack/router-plugin
// You should NOT make any changes in this file

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'

const IndexRouteWithChildren = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

export const routeTree = rootRoute.addChildren([IndexRouteWithChildren])

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteWithChildren
      parentRoute: typeof rootRoute
    }
  }
}
