/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by @tanstack/router-plugin
// You should NOT make any changes in this file

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as AdminIndexRoute } from './routes/admin/index'

const IndexRouteWithChildren = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRouteWithChildren = AdminIndexRoute.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

export const routeTree = rootRoute.addChildren([
  IndexRouteWithChildren,
  AdminIndexRouteWithChildren,
])

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteWithChildren
      parentRoute: typeof rootRoute
    }
  }
}
