/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginTestRouteImport } from './routes/admin/login-test'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminFilesIndexRouteImport } from './routes/admin/files/index'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin/employees/index'
import { Route as AdminDepartmentsIndexRouteImport } from './routes/admin/departments/index'
import { Route as AdminComponentsIndexRouteImport } from './routes/admin/components/index'
import { Route as AdminCompaniesIndexRouteImport } from './routes/admin/companies/index'
import { Route as AdminUsersFormRouteImport } from './routes/admin/users/form'
import { Route as AdminTagsFormRouteImport } from './routes/admin/tags/form'
import { Route as AdminProjectsFormRouteImport } from './routes/admin/projects/form'
import { Route as AdminFilesFormRouteImport } from './routes/admin/files/form'
import { Route as AdminEmployeesFormRouteImport } from './routes/admin/employees/form'
import { Route as AdminDepartmentsFormRouteImport } from './routes/admin/departments/form'
import { Route as AdminCompaniesFormRouteImport } from './routes/admin/companies/form'
import { Route as AdminCompaniesCompanyIdRouteImport } from './routes/admin/companies/$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginTestRoute = AdminLoginTestRouteImport.update({
  id: '/admin/login-test',
  path: '/admin/login-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/admin/tags/',
  path: '/admin/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFilesIndexRoute = AdminFilesIndexRouteImport.update({
  id: '/admin/files/',
  path: '/admin/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/admin/employees/',
  path: '/admin/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsIndexRoute = AdminDepartmentsIndexRouteImport.update({
  id: '/admin/departments/',
  path: '/admin/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComponentsIndexRoute = AdminComponentsIndexRouteImport.update({
  id: '/admin/components/',
  path: '/admin/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: '/admin/companies/',
  path: '/admin/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersFormRoute = AdminUsersFormRouteImport.update({
  id: '/admin/users/form',
  path: '/admin/users/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsFormRoute = AdminTagsFormRouteImport.update({
  id: '/admin/tags/form',
  path: '/admin/tags/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsFormRoute = AdminProjectsFormRouteImport.update({
  id: '/admin/projects/form',
  path: '/admin/projects/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFilesFormRoute = AdminFilesFormRouteImport.update({
  id: '/admin/files/form',
  path: '/admin/files/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesFormRoute = AdminEmployeesFormRouteImport.update({
  id: '/admin/employees/form',
  path: '/admin/employees/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsFormRoute = AdminDepartmentsFormRouteImport.update({
  id: '/admin/departments/form',
  path: '/admin/departments/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesFormRoute = AdminCompaniesFormRouteImport.update({
  id: '/admin/companies/form',
  path: '/admin/companies/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesCompanyIdRoute = AdminCompaniesCompanyIdRouteImport.update({
  id: '/admin/companies/$companyId',
  path: '/admin/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/login-test': typeof AdminLoginTestRoute
  '/admin': typeof AdminIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/admin/companies/form': typeof AdminCompaniesFormRoute
  '/admin/departments/form': typeof AdminDepartmentsFormRoute
  '/admin/employees/form': typeof AdminEmployeesFormRoute
  '/admin/files/form': typeof AdminFilesFormRoute
  '/admin/projects/form': typeof AdminProjectsFormRoute
  '/admin/tags/form': typeof AdminTagsFormRoute
  '/admin/users/form': typeof AdminUsersFormRoute
  '/admin/companies': typeof AdminCompaniesIndexRoute
  '/admin/components': typeof AdminComponentsIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/files': typeof AdminFilesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/login-test': typeof AdminLoginTestRoute
  '/admin': typeof AdminIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/admin/companies/form': typeof AdminCompaniesFormRoute
  '/admin/departments/form': typeof AdminDepartmentsFormRoute
  '/admin/employees/form': typeof AdminEmployeesFormRoute
  '/admin/files/form': typeof AdminFilesFormRoute
  '/admin/projects/form': typeof AdminProjectsFormRoute
  '/admin/tags/form': typeof AdminTagsFormRoute
  '/admin/users/form': typeof AdminUsersFormRoute
  '/admin/companies': typeof AdminCompaniesIndexRoute
  '/admin/components': typeof AdminComponentsIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/files': typeof AdminFilesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/login-test': typeof AdminLoginTestRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/admin/companies/form': typeof AdminCompaniesFormRoute
  '/admin/departments/form': typeof AdminDepartmentsFormRoute
  '/admin/employees/form': typeof AdminEmployeesFormRoute
  '/admin/files/form': typeof AdminFilesFormRoute
  '/admin/projects/form': typeof AdminProjectsFormRoute
  '/admin/tags/form': typeof AdminTagsFormRoute
  '/admin/users/form': typeof AdminUsersFormRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/admin/components/': typeof AdminComponentsIndexRoute
  '/admin/departments/': typeof AdminDepartmentsIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/files/': typeof AdminFilesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/admin/login-test'
    | '/admin'
    | '/admin/companies/$companyId'
    | '/admin/companies/form'
    | '/admin/departments/form'
    | '/admin/employees/form'
    | '/admin/files/form'
    | '/admin/projects/form'
    | '/admin/tags/form'
    | '/admin/users/form'
    | '/admin/companies'
    | '/admin/components'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/files'
    | '/admin/projects'
    | '/admin/tags'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/login-test'
    | '/admin'
    | '/admin/companies/$companyId'
    | '/admin/companies/form'
    | '/admin/departments/form'
    | '/admin/employees/form'
    | '/admin/files/form'
    | '/admin/projects/form'
    | '/admin/tags/form'
    | '/admin/users/form'
    | '/admin/companies'
    | '/admin/components'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/files'
    | '/admin/projects'
    | '/admin/tags'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/admin/login-test'
    | '/admin/'
    | '/admin/companies/$companyId'
    | '/admin/companies/form'
    | '/admin/departments/form'
    | '/admin/employees/form'
    | '/admin/files/form'
    | '/admin/projects/form'
    | '/admin/tags/form'
    | '/admin/users/form'
    | '/admin/companies/'
    | '/admin/components/'
    | '/admin/departments/'
    | '/admin/employees/'
    | '/admin/files/'
    | '/admin/projects/'
    | '/admin/tags/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLoginTestRoute: typeof AdminLoginTestRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCompaniesCompanyIdRoute: typeof AdminCompaniesCompanyIdRoute
  AdminCompaniesFormRoute: typeof AdminCompaniesFormRoute
  AdminDepartmentsFormRoute: typeof AdminDepartmentsFormRoute
  AdminEmployeesFormRoute: typeof AdminEmployeesFormRoute
  AdminFilesFormRoute: typeof AdminFilesFormRoute
  AdminProjectsFormRoute: typeof AdminProjectsFormRoute
  AdminTagsFormRoute: typeof AdminTagsFormRoute
  AdminUsersFormRoute: typeof AdminUsersFormRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
  AdminComponentsIndexRoute: typeof AdminComponentsIndexRoute
  AdminDepartmentsIndexRoute: typeof AdminDepartmentsIndexRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminFilesIndexRoute: typeof AdminFilesIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login-test': {
      id: '/admin/login-test'
      path: '/admin/login-test'
      fullPath: '/admin/login-test'
      preLoaderRoute: typeof AdminLoginTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/files/': {
      id: '/admin/files/'
      path: '/admin/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments/': {
      id: '/admin/departments/'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/components/': {
      id: '/admin/components/'
      path: '/admin/components'
      fullPath: '/admin/components'
      preLoaderRoute: typeof AdminComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies/': {
      id: '/admin/companies/'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/form': {
      id: '/admin/users/form'
      path: '/admin/users/form'
      fullPath: '/admin/users/form'
      preLoaderRoute: typeof AdminUsersFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags/form': {
      id: '/admin/tags/form'
      path: '/admin/tags/form'
      fullPath: '/admin/tags/form'
      preLoaderRoute: typeof AdminTagsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/form': {
      id: '/admin/projects/form'
      path: '/admin/projects/form'
      fullPath: '/admin/projects/form'
      preLoaderRoute: typeof AdminProjectsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/files/form': {
      id: '/admin/files/form'
      path: '/admin/files/form'
      fullPath: '/admin/files/form'
      preLoaderRoute: typeof AdminFilesFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees/form': {
      id: '/admin/employees/form'
      path: '/admin/employees/form'
      fullPath: '/admin/employees/form'
      preLoaderRoute: typeof AdminEmployeesFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments/form': {
      id: '/admin/departments/form'
      path: '/admin/departments/form'
      fullPath: '/admin/departments/form'
      preLoaderRoute: typeof AdminDepartmentsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies/form': {
      id: '/admin/companies/form'
      path: '/admin/companies/form'
      fullPath: '/admin/companies/form'
      preLoaderRoute: typeof AdminCompaniesFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies/$companyId': {
      id: '/admin/companies/$companyId'
      path: '/admin/companies/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AdminCompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLoginTestRoute: AdminLoginTestRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCompaniesCompanyIdRoute: AdminCompaniesCompanyIdRoute,
  AdminCompaniesFormRoute: AdminCompaniesFormRoute,
  AdminDepartmentsFormRoute: AdminDepartmentsFormRoute,
  AdminEmployeesFormRoute: AdminEmployeesFormRoute,
  AdminFilesFormRoute: AdminFilesFormRoute,
  AdminProjectsFormRoute: AdminProjectsFormRoute,
  AdminTagsFormRoute: AdminTagsFormRoute,
  AdminUsersFormRoute: AdminUsersFormRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
  AdminComponentsIndexRoute: AdminComponentsIndexRoute,
  AdminDepartmentsIndexRoute: AdminDepartmentsIndexRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminFilesIndexRoute: AdminFilesIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
