

GET {{baseUrl}}/api/user/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/user/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
	&rawParams[test]=TEST
Content-Type: application/json

###

POST {{baseUrl}}/api/user/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "email": "EMAIL",
      "username": "USERNAME",
      "password": "PASSWORD",
      "birth_date": null,
      "role": "normal",
      "last_login_at": null,
      "bio": null,
      "is_verified": false,
      "deleted_at": null
    }
  ]
}

###

POST {{baseUrl}}/api/user/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}

###

GET {{baseUrl}}/api/user/getMyIP
	?
Content-Type: application/json

###

GET {{baseUrl}}/api/user/me
	?
Content-Type: application/json

###

POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "params": {
    "email": "EMAIL",
    "password": "PASSWORD"
  }
}

###

GET {{baseUrl}}/api/user/logout
	?
Content-Type: application/json

###

POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
  "params": {
    "email": "EMAIL",
    "username": "USERNAME",
    "password": "PASSWORD",
    "role": "normal"
  }
}

###

GET {{baseUrl}}/api/user/trxTest
	?
Content-Type: application/json

###

GET {{baseUrl}}/api/tag/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/tag/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/tag/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "name": "NAME"
    }
  ]
}

###

POST {{baseUrl}}/api/tag/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}

###

GET {{baseUrl}}/api/syncFixture/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/syncFixture/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/syncFixture/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "updated_at": null,
      "name": "NAME",
      "code": null,
      "status": "draft",
      "priority": null,
      "is_active": false,
      "description": null,
      "tags": null
    }
  ]
}

###

POST {{baseUrl}}/api/syncFixture/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}

###

GET {{baseUrl}}/api/project/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/project/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/project/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "name": "NAME",
      "status": "planning",
      "description": null,
      "budget": null,
      "deadline": null,
      "image_urls": null,
      "employee_ids": [
        0
      ],
      "tag_ids": [
        0
      ]
    }
  ]
}

###

POST {{baseUrl}}/api/project/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}

###

GET {{baseUrl}}/api/project/ask
	?prompt=PROMPT
Content-Type: application/json

###

GET {{baseUrl}}/api/project/search
	?search=SEARCH
Content-Type: application/json

###

GET {{baseUrl}}/api/file/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/file/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/file/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "mime_type": "MIME_TYPE",
      "name": "NAME",
      "url": "URL"
    }
  ]
}

###

POST {{baseUrl}}/api/file/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}

###

POST {{baseUrl}}/api/file/upload
Content-Type: application/json

{}

###

POST {{baseUrl}}/api/file/uploadMultiple
Content-Type: application/json

{}

###

GET {{baseUrl}}/api/employee/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/employee/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/employee/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "user_id": 0,
      "department_id": null,
      "employee_number": "EMPLOYEE_NUMBER",
      "salary": null,
      "hire_date": null,
      "notes": null
    }
  ]
}

###

POST {{baseUrl}}/api/employee/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}

###

GET {{baseUrl}}/api/document/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/document/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
	&rawParams[semanticQuery][embedding][0]=0
	&rawParams[semanticQuery][threshold]=0
	&rawParams[semanticQuery][method]=cosine
	&rawParams[semanticQuery][which]=WHICH
	&rawParams[which]=title
Content-Type: application/json

###

POST {{baseUrl}}/api/document/findManySemanticByVector
Content-Type: application/json

{
  "subset": "unknown",
  "params": {
    "num": 24,
    "page": 1,
    "search": "id",
    "keyword": "KEYWORD",
    "orderBy": "id-desc",
    "queryMode": "both",
    "id": 0,
    "semanticQuery": {
      "embedding": [
        0
      ],
      "threshold": 0,
      "method": "cosine",
      "which": "WHICH"
    },
    "which": "title"
  }
}

###

GET {{baseUrl}}/api/document/embedQuery
	?text=TEXT
	&model=voyage
	&inputType=document
Content-Type: application/json

###

POST {{baseUrl}}/api/document/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "title": "TITLE",
      "content": null,
      "status": "draft",
      "title_content_embedding": null
    }
  ]
}

###

POST {{baseUrl}}/api/document/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}

###

GET {{baseUrl}}/api/department/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/department/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
	&rawParams[company_name]=COMPANY_NAME
Content-Type: application/json

###

POST {{baseUrl}}/api/department/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "name": "NAME",
      "company_id": 0,
      "parent_id": null
    }
  ]
}

###

POST {{baseUrl}}/api/department/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}

###

GET {{baseUrl}}/api/company/findById
	?subset=unknown
	&id=0
Content-Type: application/json

###

GET {{baseUrl}}/api/company/findMany
	?subset=unknown
	&rawParams[num]=24
	&rawParams[page]=1
	&rawParams[search]=id
	&rawParams[keyword]=KEYWORD
	&rawParams[orderBy]=id-desc
	&rawParams[queryMode]=both
	&rawParams[id]=0
Content-Type: application/json

###

POST {{baseUrl}}/api/company/save
Content-Type: application/json

{
  "spa": [
    {
      "id": 0,
      "created_at": "2000-01-01",
      "name": "NAME"
    }
  ]
}

###

POST {{baseUrl}}/api/company/del
Content-Type: application/json

{
  "ids": [
    0
  ]
}