version: "3.8"
name: ${CONTAINER_NAME}
services:
  pg:
    platform: linux/arm64
    image: postgres:18
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: template1
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "${DB_PORT}:5432"
