name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.23.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Remove sonamu.lock and sync in miomock-api
        run: |
          # miomock-api의 sonamu.lock 파일을 지우고 cli로 sync를 실행하여, 템플릿을 사용하여 파일들을 새로 만들도록 합니다.
          rm examples/miomock/api/sonamu.lock && pnpm --filter miomock-api sonamu sync

          # 만약 이 작업으로 인해 변경된 파일이 있다면, 이는 템플릿의 변경을 생성된 코드가 못 따라간 것이니 경고를 출력합니다.
          CHANGED_FILES=$(git diff --name-only)
          if [ -n "$CHANGED_FILES" ]; then
            FILE_LIST=$(echo "$CHANGED_FILES" | sed 's/^/  - /' | paste -sd '\n' -)
            echo "::warning::The following files in miomock-api were changed after sonamu sync:"$'\n'"$FILE_LIST"
          fi

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: pnpm publish-those-not-published-yet
