name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Setup PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'miomock123';"
          sudo -u postgres psql -c "CREATE DATABASE miomock;"
          PGPASSWORD=miomock123 psql -U postgres -d miomock -h 127.0.0.1 -f examples/miomock/api/database/fixtures/init.sql

      # sonamu.lock 지우고 sync가 잘 되는지 봅니다.
      - name: Miomock sync test
        run: scripts/miomock-sync-test.sh

      # miomock-api와 miomock-web이 제대로 실행되는지 봅니다.
      - name: Miomock smoke test
        run: scripts/miomock-smoke-test.sh

      # miomock-api의 테스트를 실행합니다.
      - name: Miomock unit test
        run: scripts/miomock-unit-test.sh

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: pnpm publish-those-not-published-yet
